### PR TITLE
Filters out unpublished posts from landing page.

### PR DESCRIPTION
**Pull request by kristoferjoseph**
We could also 404 if someone navigates directly to an unpublished post. 
@macdonst what thinks you?

### CODE REVIEW

**Comment by macdonst** [comment]
@kristoferjoseph it would be nice to have a 404 if it's an unpublished post.

Also, I'd add a check to see if today's date is before the date in `frontmatter.published`. If it is then it shouldn't show up in the  list of posts.

**Comment by kristoferjoseph** [comment]
@macdonst Then we should have a bit longer discussion.
What format would you like to author published dates in?

Currently they are in the format:
'December 21, 2020'

This was probably chosen since this is what the current display format is.

Do you like this format or should we do something like a UTC timestamp so we can compare UTC for today and format in the view to a locale specific format?

**Comment by kristoferjoseph** [comment]
Plan is
- leave date format in post alone
- parse existing date format to UTC pacific
- compare Date.today to post date

**Comment by kristoferjoseph** [comment]
This relies on https://github.com/beginner-corp/blog.begin.com/pull/49

**Pull request merged**
