### PR TITLE
add padding to code pre tags

### LINKED ISSUE #20: Adding padding to pre element so copy button is not cut off
Make the Copy button look good for one line code blocks.

Screen Shot 2021-09-30 at 4 45 01 PM

### PR DESCRIPTION
**Pull request by tbeseda**
Help with spacing and preventing "Copy" button overflow on one-liners

image

fixes #20

### CODE REVIEW

**Review by macdonst — APPROVED** [review]
LGTM!

**Comment by kristoferjoseph** [comment]
DOPE.

**Comment by kristoferjoseph** [comment]
Should we have the copy button be hidden by default?
Then fade it in when the user interacts with the code?
Might keep the button from obscuring code.

**Comment by macdonst** [comment]
@kristoferjoseph yes, this is a great idea. The copy button always gets in the way of long complicated CLI commands which is when you really want to use it.

**Pull request merged**
