### PR TITLE
💄  Issue #35: Hide Copy Button until user mouse over

### PR DESCRIPTION
**Pull request by macdonst**
Fixes issue #35 

The copy button remains hidden until you mouse over the `pre` element:

blawg-pre-mouse-over

on mobile the button is hidden by default and only shows up when you tap on the `pre` element:

blawg-pre-mouse-over-mobile

### CODE REVIEW

**Comment by tbeseda** [comment]
A thought about how we might make the button less intrusive on single line code blocks without toggling visibility: maybe use an icon + smaller padding?

Github has this, albeit not on top of a piece of code.

copy

**Comment by macdonst** [comment]
By popular demand I've switched to icons and gotten rid of the only appear on hover code. 

Looks good on desktop:

blawg-pre-copy

Still have the same issue on mobile where the button can overlap the code:

blawg-pre-copy-mobile

**Comment by macdonst** [comment]
Going to wait until shiki lands and fix this one.

**Comment by macdonst** [comment]
Needs a refactoring after the latest changes.

**Comment by macdonst** [comment]
Closing this PR as we need a new approach because of shiki.

**Pull request closed without merging**
